eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#For not override other properties in case of inherit
spring:
  cloud:
    config:
      override-system-properties: false
