spring:
  data:
    mongodb:
      username: shah
      password: shah
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  application:
    name: customer-service
server:
  port: 8090
